### ISSUE TITLE
Alternative Weights Location

### ISSUE THREAD

**Issue by jfischoff** [chenxx89/BFRffusion#2]
I'm struggling to get the BaiduNetdisk to work. Could you upload the weights to Huggingface instead?

**Comment by chenxx89** [comment]
Now you can download our weights from [OneDrive](https://mail2sysueducn-my.sharepoint.com/:u:/g/personal/chenxx89_mail2_sysu_edu_cn/EbMHkGqhYUVDndHy5fVlNo4BVMAZ3161X9FR_T_utTYuCA). Hope this could help you.

**Comment by jfischoff** [comment]
Downloading now, thank you!
