### ISSUE TITLE
White spotlight effect on inference images with custom-trained model

### ISSUE THREAD

**Issue by luser350** [chenxx89/BFRffusion#8]
Hi, 
I am training a model on my dataset. It shows good results saved by the training script during validation. But when I use a saved checkpoint file with the provided inference script it gives a white spotlight effect to the output. It also produces flipped output sometimes. Here is an example
Input
![input](https://github.com/user-attachments/assets/d1d1387e-7c17-43bd-857c-3ef2cd46cb88)
Val Output
![gen_val](https://github.com/user-attachments/assets/293e7efe-de69-408f-abad-180f2d586536)
Inf Output
![gen_inf](https://github.com/user-attachments/assets/357bbde8-c658-4e05-8815-fd2581b170dd)

I am looking forward to your kind help.

**Comment by chenxx89** [comment]
There may be some bugs in the image input/output normalization of the inference script. You can try using the test script to process the aligned images, which is similar to the validation.

**Comment by luser350** [comment]
Thanks. Solved it by adding normalization and hflip in preprocessing. Just for my information did you train your model without normalization and hflip preprocessing?

**Comment by chenxx89** [comment]
We use flip preprocessing randomly and normalize the lq images to [0, 1] following ControlNet when we train our model.

**Comment by baiguiang** [comment]
![000](https://github.com/user-attachments/assets/fba70288-5dd7-4037-b8c8-c150bedd1a1e)
Hello, I see that you successfully run this code, but when I try to reproduce it, I always get stuck after running an epoch, and then it says' CUDA out of memory ', in fact, I must have enough memory, I would like to know how you reproduce it, what is your environment configuration or what changes have been made, thank you very much.
